POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzMyODQ0MTAyLCJ1c2VySWQiOjF9.02Qhr1pTVtE8Yp0XpDy3vr7Myd6ub8ch5gkZBaQOPmI

{
    "name": "Test event",
    "description": "a Test event",
    "location": "Test location",
    "dateTime": "2024-11-11T13:30:00.000Z"
}
