DELETE http://localhost:8080/events/6
# authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzMyODQ0MTAyLCJ1c2VySWQiOjF9.02Qhr1pTVtE8Yp0XpDy3vr7Myd6ub8ch5gkZBaQOPmI
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3N0QGdtYWlsLmNvbSIsImV4cCI6MTczMjg0NDk0MywidXNlcklkIjoyfQ.IUN6k3_fjoJdhFxoE7wo_1_YLkifMTjGKn70ei_jv2E