POST http://localhost:8080/events/1/register
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3N0QGdtYWlsLmNvbSIsImV4cCI6MTczMjg1NzA5NCwidXNlcklkIjoyfQ.Np7jXoE_U4cH8S81rZw_cdB9s0wJKNL3uKuq0o_8TeA
